### ISSUE TITLE
pls help me

### ISSUE THREAD

**Issue by python-hmv** [CTK-WARRIOR/Discord-Bot-Dashboard#10]
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/Discord-Bot-Dashboard-1/node_modules/node-fetch/src/index.js from /home/runner/Discord-Bot-Dashboard-1/bot/commands/info/anime.js not supported.
Instead change the require of index.js in /home/runner/Discord-Bot-Dashboard-1/bot/commands/info/anime.js to a dynamic import() which is available in all CommonJS modules.
    at n (/home/runner/Discord-Bot-Dashboard-1/node_modules/jiti/dist/v8cache.js:2:2472)
    at Object.<anonymous> (/home/runner/Discord-Bot-Dashboard-1/bot/commands/info/anime.js:2:15)
    at Module.o._compile (/home/runner/Discord-Bot-Dashboard-1/node_modules/jiti/dist/v8cache.js:2:2778)
    at n (/home/runner/Discord-Bot-Dashboard-1/node_modules/jiti/dist/v8cache.js:2:2472)
    at /home/runner/Discord-Bot-Dashboard-1/bot/handlers/command.js:18:24
    at Array.forEach (<anonymous>)
    at module.exports (/home/runner/Discord-Bot-Dashboard-1/bot/handlers/command.js:10:62)
    at /home/runner/Discord-Bot-Dashboard-1/bot/index.js:12:35
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/runner/Discord-Bot-Dashboard-1/bot/index.js:11:23)
    at Module.o._compile (/home/runner/Discord-Bot-Dashboard-1/node_modules/jiti/dist/v8cache.js:2:2778)
    at Object.<anonymous> (/home/runner/Discord-Bot-Dashboard-1/server.js:25:1) {
  code: 'ERR_REQUIRE_ESM'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dashboard-nuxt@1.0.0 start: `NODE_ENV=production node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the dashboard-nuxt@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-10-22T13_14_24_720Z-debug.log
exit status 1

**Comment by Adityapro9** [comment]
Wait
